apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: martikan/ticketing-auth:0.0.3
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 4000
          env:
            - name: DATASOURCE_URL
              value: "mongodb://mongo-srv:27017"
            - name: DATASOURCE_DB
              value: auth
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: JWT_KEY
                  name: jwt-secret
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 4000
      targetPort: 4000
